server:
  port: 8081
#  servlet:
#      context-path:
#  context-path: /portal
#  undertow:
#    accesslog:
#      dir:
#      prefix: access_log.
#      pattern: common
#      rotate: true
#      suffix:
#    direct-buffers: true
#    buffer-size: 10240
#    max-http-post-size: 10
#    io-threads: 16
#    worker-threads: 256

spring:
  profiles:
    include: test-dao,test-redis
  aop:
    proxy-target-class: false

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@192.168.1.165:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    prefer-ip-address: true
