server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.165:8761/eureka/
    instance:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true