#  servlet:
#      context-path:
#  context-path: /portal
#  undertow:
#    accesslog:
#      dir:
#      prefix: access_log.
#      pattern: common
#      rotate: true
#      suffix:
#    direct-buffers: true
#    buffer-size: 10240
#    max-http-post-size: 10
#    io-threads: 16
#    worker-threads: 256

spring:
  profiles:
    include: dev-dao,dev-redis

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@192.168.1.165:58761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
