server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: user-center-backend
  session:
    store-type: redis
logging:
  config: classpath:logback.xml
ribbon:
  #请求处理的超时时间
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 30000

